### ISSUE TITLE
Environment variables added multiple times

### ISSUE THREAD

**Issue by arturdzm** [vmware-labs/service-bindings#67]
If someone or something removes `internal.service.binding/projection-....` annotation from application resource (eg Deployment) environment variables are aded more then once in infinite reconcile loop.

**Comment by scothis** [comment]
Yea, those fields are essential to know what values were contributed vs preexisting on the resource before it's injected. Since we have a mutation webhook already intercepting all mutations on those resources, we can prevent any authority that isn't the service binding controller from removing that field.

I'm curious if we could mildly abuse the finalizers to encode this data there? A controlling owner would never expect to control the finalizers unlike annotations which it may try to control.
